version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - label-generator
      - glabels-templates
      # - grocy
      # - office

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:80"
    depends_on:
      - backend

  grocy:
    build: ./services/grocy
    ports:
      - "8005:8000"
    environment:
      GROCY_URL: "http://grocy.app.lan/api"
      GROCY_API_KEY: "uCZnD4sXW12WgDVk3p3ujasVZgQl2KiBKvLJRa8jwRom1UdFI5"

  office:
    build: ./services/office
    ports:
      - "8004:8000"

  label-generator:
    build: ./services/label-generator
    ports:
      - "8002:8000"
    depends_on:
      - glabels-templates

  glabels-templates:
    build: ./services/glabels-templates
    ports:
      - "8003:8000"